protected/controllers/AppController.php
<?php

class AppController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = 'main';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array( 'search'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'view'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $this->layout = "column1";
        $model = new App;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['App'])) {
            $model->attributes = $_POST['App'];
            if ($model->save())
                $this->redirect(array('admin'));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $this->layout = "column1";
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['App'])) {
            $model->attributes = $_POST['App'];
            if ($model->save())
                $this->redirect(array('admin'));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }
    


    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('App');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        )); 
    }

    /**
     * Manages all models.
     */
    public function actionSearch() {
        
        $criteria = new CDbCriteria();
        $appname='寻找您需要的APP';
        if (isset($_POST['appname'])) {
             $criteria->compare('appname',$_POST['appname'] , true);
             $appname=$_POST['appname'];
        } else {

            $this->redirect(array('plat/index'));
        }
       
        $criteria->order = 'create_time desc';
        $count = App::model()->count($criteria);

        $pager = new CPagination($count);
        $pager->pageSize = 10;
        $pager->applyLimit($criteria);

        $apps = App::model()->findAll($criteria);

        $this->render('search', array('pages' => $pager, 'apps' => $apps,'appname'=>$appname));

    }

    public function actionAdmin() {
        $this->layout='column1';
        $model = new App('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['App']))
            $model->attributes = $_GET['App'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return App the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = App::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param App $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'app-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
    
    

}

protected/controllers/EnumController.php
<?php

class EnumController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(''),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','view','index'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Enum;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Enum']))
		{
			$model->attributes=$_POST['Enum'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Enum']))
		{
			$model->attributes=$_POST['Enum'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Enum');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Enum('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Enum']))
			$model->attributes=$_GET['Enum'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Enum the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Enum::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Enum $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='enum-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/JobsController.php
<?php

class JobsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(""),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','view'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Jobs;
                $model->post_time=date("Y-m-d");

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Jobs']))
		{
			$model->attributes=$_POST['Jobs'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Jobs']))
		{
			$model->attributes=$_POST['Jobs'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Jobs');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Jobs('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Jobs']))
			$model->attributes=$_GET['Jobs'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Jobs the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Jobs::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Jobs $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='jobs-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/admin.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <!-- blueprint CSS framework -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/css/screen.css" media="screen, projection" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/css/print.css" media="print" />
        <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/css/ie.css" media="screen, projection" />
        <![endif]-->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/css/main.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/css/form.css" />
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl; ?>/favicon.ico" />
        <script src="<?php echo Yii::app()->BaseUrl; ?>/js/jquery-1.6.2.min.js"></script>
        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    </head>
    <body>
        <div class="container" id="page">
            <div id="header">
                <div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
            </div><!-- header -->
            <div id="mainmenu">
                <?php
                $this->widget('zii.widgets.CMenu', array(
                    'items' => array(
                        array('label' => '阳光动态', 'url' => array('article/admin')),
                        array('label' => '需求-云方案', 'url' => array('message/admin')),
                        array('label' => '联系-云桌面', 'url' => array('contact/admin')),
                        array('label' => '客户案例', 'url' => array('cases/admin')),
                        array('label' => '招聘管理', 'url' => array('jobs/admin')),
                        array('label' => '关于我们', 'url' => array('about/admin')),
                        array('label' => 'Apps', 'url' => array('app/admin')),
                        array('label' => '类型管理', 'url' => array('enum/admin')),
                        array('label' => 'Login', 'url' => array('yovoleAdmin/login'), 'visible' => Yii::app()->user->isGuest),
                        array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('yovoleAdmin/logout'), 'visible' => !Yii::app()->user->isGuest)
                    ),
                ));
                ?>
            </div><!-- mainmenu -->
            <?php
            $this->widget('zii.widgets.CBreadcrumbs', array(
                'homeLink' => CHtml::link('Home', array('yovoleAdmin/')),
                'links' => $this->breadcrumbs,
            ));
            ?><!-- breadcrumbs -->
            <?php echo $content; ?>
            <div style="clear:both"></div>
            <div id="footer">
                Copyright &copy;
                <?php
                @ini_set('date.timezone', 'Asia/Shanghai');
                echo date('Y');
                ?> by 上海有孚计算机网络有限公司 .<br/>
                All Rights Reserved.<br/>
                <?php echo Yii::YFpowered(); ?>
            </div><!-- footer -->
        </div><!-- page -->
    </body>
</html>

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/admin'); ?>
<div class="span-19"style="width:1000px;">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>

<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>

<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/admin'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="keywords" content="阳光云,云计算,有孚,阳光互联,有孚网络,云平台,云方案,云桌面,私有云,解决方案,云主机"/>
        <meta name="description" content="阳光云是上海有孚计算机网络有限公司旗下品牌，是一个基于WEB服务整合了计算、存储与网络资源的弹性云技术Iaas平台。提供云平台、云方案、云桌面等云计算服务"/>
        <meta name="baidu-site-verification" content="cDi77Gf75G"/>
        <script src="<?php echo Yii::app()->BaseUrl; ?>/js/jquery-1.6.2.min.js"></script>
        <title><?php echo CHtml::encode($this->pageTitle); ?> - 基于WEB服务整合了计算、存储与网络资源的弹性云技术Iaas平台|云平台|云方案|云桌面 </title>
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/cloud.css" />
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.ico" />
    </head>
    <body>
        <div class="container" id="page">
            <div class="ding ov">
                <div class="w1000">
                    <iframe src="http://my.suncloud.cn/is_logged.html" frameBorder="0" scrolling="no" width="100%" height="100%" marginwidth="0" marginheight="0" hspace="0" vspace="0" allowTransparency="true" ></iframe>
                </div>
            </div>
            <div class="head w1000 ov">
                <div class="logo z"><a href="<?php echo $this->gameHost; ?>"><img src="<?php echo Yii::app()->baseUrl; ?>/images/logo.jpg" /></a></div>
                <!--备案icon start-->
                <div class="ba_icon y"><a href="http://icp.sundns.com/" target="_blank"><img src="images/ba_icon.gif" alt="备案" /></a></div>
                <!--备案icon end-->
                <div id="navMenu" class="y" >
                    <ul>
                        <li><a href='<?php echo $this->gameHost; ?>/index.html'>主页</a></li>
                        <li><a href='<?php echo $this->gameHost; ?>/host.html'  rel='dropmenu1' >产品＆服务</a></li>
                        <li  class="onelink"><a href="javascript:void(0);"  rel='dropmenu2' >行业云</a></li>
                        <li><a href='<?php echo $this->gameHost; ?>/suport.html' rel="dropmenu3" >技术支持</a></li>
                        <li><a href='<?php echo $this->gameHost; ?>/about-company.html'  rel='dropmenu4' >关于我们</a></li>
                    </ul>     
                </div>
                <script type='text/javascript' src="<?php echo Yii::app()->baseUrl; ?>/js/menu.js"></script>
                <ul id="dropmenu1" class="dropMenu" >
                    <li><dl style="height:50px;margin-bottom:20px; border-bottom:1px dotted #aaa; line-height:35px;"><dt>计算和网络</dt><dd><A href="<?php echo $this->gameHost; ?>/host.html">云主机</A><A href="<?php echo $this->gameHost; ?>/balance.html">负载均衡</A><A href="<?php echo $this->gameHost; ?>/defend.html">云防护</A></dd></dl></li>
                    <li><dl><Dt>存储和CDN</Dt>
                            <dd class="amb"><A href="<?php echo $this->gameHost; ?>/disk.html" >云硬盘</A><A href="<?php echo $this->gameHost; ?>/database.html">云数据库</A><div class="cl ov" style="height:0"></div><A href="<?php echo $this->gameHost; ?>/memory.html">云内存存储</A><A href="<?php echo $this->gameHost; ?>/distribute.html">云分发CDN</A></dd></dl></li>
                </ul>

                <ul id="dropmenu2" class="dropMenu">
                    <li><a href="/" target="_blank">游戏云</a></li>
                    <li><a href="<?php echo $this->createUrl('sunapp/'); ?>" target="_blank">阳光云平台</a></li>
                    <li><a href="<?php echo $this->createUrl('solution/'); ?>" target="_blank">阳光云方案</a></li>
                    <li><a href="<?php echo $this->createUrl('desktop/'); ?>" target="_blank">阳光云桌面</a></li>
                </ul>


                <ul id="dropmenu3" class="dropMenu">
                    <li><a href="http://docs.suncloud.cn/" target="_blank">产品说明手册</a></li>
                </ul>

                <ul id="dropmenu4" class="dropMenu">
                    <li><a href="<?php echo $this->gameHost; ?>/about-company.html" >公司介绍</a></li>
                    <li><a href="<?php echo $this->gameHost; ?>/about-contact.html" >联系我们</a></li>
                </ul>
                <script type="text/javascript">cssdropdown.startchrome("navMenu")</script> 

            </div>

            <?php echo $content; ?>
            <div class="clear"></div>
            <div id="foot" class="ov">
                <div class="w1000">
                    <div class="ft-lg z"><img src="images/ft-lg.gif" /></div>
                    <div class="y">
                        <ul class="ulprd" style="width:210px;">
                            <li class="tit" style="width:120px;padding-right:80px;"><a href="<?php echo $this->gameHost; ?>/host.html">产品＆服务</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/host.html">云主机</a></li>
                            <li><a href="<?php echo $this->gameHost;
            ; ?>/balance.html">负载均衡</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/disk.html">云硬盘</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/defend.html">云防护</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/memory.html">云内存存储</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/distribute.html">云分发CDN</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/database.html">云数据库</a></li>
                            <li><a href="http://my.suncloud.cn/#/dns_domain">DNS</a></li>
                        </ul>
                        <ul>
                            <li class="tit"><a href="javascript:void(0);">行业云</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>" target="_blank">游戏云</a></li>
                            <li><a href="<?php echo $this->createUrl('sunapp/'); ?>" target="_blank">阳光云平台</a></li>
                            <li><a href="<?php echo $this->createUrl('solution/'); ?>" target="_blank">阳光云方案</a></li>
                            <li><a href="<?php echo $this->createUrl('desktop/'); ?>" target="_blank">阳光云桌面</a></li>
                        </ul>
                        <ul>
                            <li class="tit"><a href="<?php echo $this->gameHost; ?>/suport.html">技术支持</a></li>
                            <li><a href="http://docs.suncloud.cn/" target="_blank">产品说明手册</a></li>
                        </ul>
                        <ul>
                            <li class="tit"><a href="<?php echo $this->gameHost; ?>/about-company.html">关于我们</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/about-company.html" >公司介绍</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>/about-contact.html" >联系我们</a></li>
                            <li><a href="<?php echo $this->gameHost; ?>" target="_blank">阳光云suncloud</a></li>
                            <li><a href="http://www.sundns.com/" target="_blank">阳光互联</a></li>
                        </ul>
                        <div class="cl"></div>
                        <p>Copyright ©2013 上海有孚计算机网络有限公司 沪B1.B2-20040073</p>
                    </div>
                </div>
            </div>
            <div style="display:none;">
                <script type="text/javascript">
                    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
                    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F23e0a70d96dab9450f603b2e730e84a6' type='text/javascript'%3E%3C/script%3E"));
                </script>
            </div>
        </div>
    </body>
</html>